server:
  port: 8080 # 服务启动端口

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接 Docker 里的 MySQL
    url: jdbc:mysql://localhost:3306/lark_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

# MyBatis Plus 配置：打印 SQL
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl