version: '3'
services:
  # 1. 数据库 MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql_lark
    environment:
      MYSQL_ROOT_PASSWORD: root  # <--- 看这里！你的密码是 root
      MYSQL_DATABASE: lark_db    # <--- 初始数据库名
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  # 2. 缓存 Redis (顺手加上，后面复健要用)
  redis:
    image: redis:alpine
    container_name: redis_lark
    ports:
      - "6379:6379"