version: '3'
services:
  # 1. 数据库 MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql_lark
    environment:
      MYSQL_ROOT_PASSWORD: root  #
      MYSQL_DATABASE: lark_db    # 数据库名
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  # 2. 缓存 Redis
  redis:
    image: redis:alpine
    container_name: redis_lark
    ports:
      - "6379:6379"
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper_lark
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka_lark
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper